# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'howareyou' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Parse'
  # Pods for howareyou

  target 'howareyouTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'howareyouUITests' do
    # Pods for testing
  end

end
